#!/usr/bin/env bash
SSLP=`openssl rand -base64 12 | tr -cd '[:alnum:]'`
cat ./kubernetes/kubegres/postgres-login.yaml | sed -e "s/superUserPasswordGoesHere/$SSLP/g" -e "s/replicaPasswordGoesHere/$SSLP/g" | kubectl apply -f -