#!/usr/bin/env bash
SCR=$(kubectl get secret clu-psql-secret -o jsonpath="{.data.superUserPassword}" | base64 --decode)
kubectl exec -it pg-client -- /bin/bash -c "PGPASSWORD=$SCR  psql -h clu-psql -U postgres"
