name: Silly Pun CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    

    - name: Build a Quarkus native application
      uses: maxday/quarkus-native-build-docker-action@1
      with:
        outputName: silly-pun-generator-1.0.0-SNAPSHOT-native-image
        
    - name: Upload native executable
      uses: actions/upload-artifact@v1
      with:
        name: native-executable
        path: silly-pun-generator-1.0.0-SNAPSHOT-native-image      

