name: Silly Pun CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: build with maven (UberJaR)
      run: make packageuber

    - run: mkdir staging && cp -v target/silly-pun-generator-*-runner.jar staging
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging
