name: Silly Pun CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    

    - name: Build native executable
      uses: maxday/quarkus-native-build-docker-action@13bf5c4ae6942143cf43a5663a6c7f847ac3163c
      with:
        outputName: sillypunserver-runner
    - name: Upload native executable
      uses: actions/upload-artifact@v1
      with:
        name: native-executable
        path: sillypunserver-runner      

