name: Silly Pun CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: get version number
      id: runver
      run: echo "::set-output name=runver::$(date +'%Y%m%d-%H%M%S')"
    - name: build with maven (UberJaR)
      run: make packageuber

    - run: mkdir staging && cp -v target/silly-pun-generator-runner.jar staging/silly-pun-generator-server.jar
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: staging/*
        tag: release-${{ steps.runver.outputs.runver }}
        overwrite: true
        file_glob: true
        release_name: release-${{ github.sha }}
